### ISSUE TITLE
Ruby 2.3.1 build issues on Mac OS X El Capitan 10.11.6

### ISSUE THREAD

**Issue by pc-mreeves** [rbenv/ruby-build#992] opened 2016-09-09 18:37 UTC
I am getting an odd error when building 2.3.1. I get one of two errors:

```
BUILD FAILED (OS X 10.11.6 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20160909104415.25429
Results logged to /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20160909104415.25429.log

Last 10 log lines:
compiling vm_backtrace.c
compiling vm_trace.c
compiling thread.c
compiling cont.c
compiling ./missing/explicit_bzero.c
compiling ./missing/setproctitle.c
compiling dmyenc.c
make: ./config.status: Permission denied
make: *** [ruby-runner.c] Error 1
make: *** Waiting for unfinished jobs....
```

or

```
BUILD FAILED (OS X 10.11.6 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20160909110514.33878
Results logged to /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20160909110514.33878.log

Last 10 log lines:
compiling enc/unicode.c
compiling enc/utf_8.c
compiling enc/trans/newline.c
linking miniruby
generating encdb.h
make: ./miniruby: Permission denied
make: ./miniruby: Permission denied
make: *** [.rbconfig.time] Error 1
make: *** Waiting for unfinished jobs....
make: *** [encdb.h] Error 1
```

I have checked and there is nothing strange about the perms of these files. Perhaps antivirus or something like that is the culprit? 

However if I cd `/var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20160909110514.33878/ruby-2.3.1` and run `make install` it seems to install it successfully to `~/.rbenv/versions/`

Any ideas or can I provide more information? Does installing ruby 2.3.1 this way cause any problems? `make test` also passed.

**Comment by erikphansen** [comment] 2016-09-14 23:33
I'm getting different errors in a similar environment.

```
❯ rbenv install 2.3.1                                                       0 < 16:24:46
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...

BUILD FAILED (OS X 10.11.6 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/lj/kndx6mlx3flcd0gl8xp7__680000gn/T/ruby-build.20160914162742.65586
Results logged to /var/folders/lj/kndx6mlx3flcd0gl8xp7__680000gn/T/ruby-build.20160914162742.65586.log

Last 10 log lines:
  Referenced from: /private/var/folders/lj/kndx6mlx3flcd0gl8xp7__680000gn/T/ruby-build.20160914162742.65586/ruby-2.3.1/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /private/var/folders/lj/kndx6mlx3flcd0gl8xp7__680000gn/T/ruby-build.20160914162742.65586/ruby-2.3.1/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

make: *** [encdb.h] Trace/BPT trap: 5
make: *** Waiting for unfinished jobs....
make: *** [.rbconfig.time] Trace/BPT trap: 5
```

Puzzled by the references to `built for Mac OS X 10.12` which doesn't officially come out for a week or so. I'm running 10.11.6

**Comment by stenlarsson** [comment] 2016-09-15 14:21
I hade the second problem described here, probably because Xcode was upgraded. Solved by running
```
xcode-select --install
```

**Comment by erikphansen** [comment] 2016-09-15 14:35
@stenlarsson nailed it. Thanks!

Seems that installing Xcode on a new machine doesn't automatically install the command line tools. Could have sworn that used to be the case. Or at least they would prompt you to.

**Comment by mislav** [comment] 2016-09-15 14:44
@pc-mreeves Might that be the cause of your problems as well?

**Comment by pc-mreeves** [comment] 2016-09-15 16:44
It could definitely be related. However, IIRC I did not need to run that command because I ran the homebrew install first which installs the command line tools: 
`https://raw.githubusercontent.com/Homebrew/install/master/install`

If I try to run it again I get this:
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

I'll update and see if that fixes the issue... (after 3.44 gigs (!!!) downloads and installs...)

**Comment by josephgrossberg** [comment] 2016-10-01 00:18
@pc-mreeves Did the App Store download fix the problem for you?

**Comment by pc-mreeves** [comment] 2016-10-03 17:26
Unfortunately no... As I mentioned I had manually run `make install` on 2.3.1 so I didn't want to re-install that. So I tested by installing 2.2.5 and got the same error "make: ./miniruby: Permission denied". I suspect it might be Sophos antivirus or some other random culprit. 

I can still cd to the directory and run make install and then it works.

**Comment by josephgrossberg** [comment] 2016-10-03 17:32
@pc-mreeves Thank you for the reply!

May I ask: when you say, "I can still `cd` to the directory and run `make install` and then it works." which directory are you referring to?

**Comment by pc-mreeves** [comment] 2016-10-03 17:45
When the `rbenv install 2.2.1 -v` command fails it says something like (note this is a different error though):
```
/var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20161003102300.18142 /
Downloading ruby-2.2.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.1.tar.bz2
/usr/local/bin/ruby-build: line 382: ./bin/rm: No such file or directory

BUILD FAILED (OS X 10.11.6 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20161003102300.18142
Results logged to /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20161003102300.18142.log
```

If I cd to /var/folders/_y/qc89fk7n3m1f1p5pt8kpsgvdv009dp/T/ruby-build.20161003102300.18142 I can run `make install` and it will complete successfully.

**Comment by josephgrossberg** [comment] 2016-10-03 18:41
Confirmed -- I got the same output re: `miniruby` permissions, and a `make install` solved it. Thanks for documenting this.

I'll also note my ruby is `2.3.1`. Apparently this problem occurs on multiple versions of ruby. Thank you for documenting a workaround.

**Comment by phpmaps** [comment] 2016-10-24 04:47
@pc-mreeves thank you for your suggestion to ``` cd ``` into the ``` working tree ``` ie. /var/folders/jj/wc_0mglj53x4rlnqxl9yzkk467jj82/T/ruby-build.20161023213421.54245 and then run ``` make install ```  after i did this ruby 2.3.1 successfully built!   Then to start using the latest version I had to write ``` rbenv global 2.3.1 ``` to my terminal.

**Comment by zwang** [comment] 2016-11-12 16:02
It seem for 2.3.1, under the working tree, there is another folder called `ruby-2.3.1`, needs to go there and then `make install` to install the ruby 2.3.1

**Comment by recyclablestudios** [comment] 2016-11-17 12:56
I'm getting this when make install..

JM:ruby-build.20161117072715.65539 jm$ make install
make: *** No rule to make target `install'.  Stop.
JM:ruby-build.20161117072715.65539 jm$

**Comment by athrunsun** [comment] 2016-12-26 07:20
I got the same error when I was trying to install ruby 2.4.0 on OSX Yosemite 10.10.5.

Why do I have to append an `sudo` before `rbenv install 2.4.0`? I thought rbenv is installing everything into my `~/.rbenv`, isn't that the truth?

I think prefixing install command with `sudo` defeat the purpose of having rbenv in home folder.

**Comment by mislav** [comment] 2019-02-12 13:38
Closing due to staleness. If there is more recent information, steps to reproduce, workarounds, please open a new issue! 🙇

**Closed by mislav** 2019-02-12 13:38 UTC

**Comment by tleish** [comment] 2019-03-07 15:07
Our team still has this issue.

```
ruby-build: use openssl from homebrew
Downloading ruby-2.6.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.1.tar.bz2
Installing ruby-2.6.1...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.14.3 using ruby-build 20190130)

Inspect or clean up the working tree at /var/folders/fj/wd8pp7d54rj2gmklzybhx0_r78033x/T/ruby-build.20190307074938.84367
Results logged to /var/folders/fj/wd8pp7d54rj2gmklzybhx0_r78033x/T/ruby-build.20190307074938.84367.log

Last 10 log lines:
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
compiling ./main.c
compiling dmydln.c
make: ./tool/darwin-cc: Permission denied
make: ./tool/darwin-cc: Permission denied
make: *** [main.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [dmydln.o] Error 1
```
In my particular case, the machine is new install of MacOS (vs upgraded) with:
* MacOS 10.14.3 (Mojave) 
* Homebrew 2.0.3
* Xcode 10.1
* ruby-build 20190130

Workaround to `cd /var/folders/.../ruby-2.6.1` and run `make install` from original post still works.

What can we do to help troubleshoot and find resolution?

**Comment by nachocases** [comment] 2019-03-22 03:35
I had the same problem and was able to finally solve it (I was trying to install using rbenv but also rvm was failing for me with the same error). Basically my problem was with MacPorts, I had to upgrade macports (by reinstalling it) and then port selfupdate, port upgrade outdated and found the issue when this failed for gcc, then I've run port uninstall obsolete, once I did that, rbenv worked like a charm

**Comment by vitorreis** [comment] 2019-07-12 09:58
July 2019, this still happens.... workaround... cd into the folder of the build and `make install`

**Comment by 3rdfoundation** [comment] 2019-08-30 16:43
This is still a problem. I don't compile stuff very often so this was an all-morning struggle. 

**To provide some specifics for others in this situation:**
I was patching 2.4.2 ruby so that ruby-prof could dump memory.
> https://github.com/skaes/rvm-patchsets

After downloading the patches, this was the command that failed with the permission issue:
`cat *.patch | rbenv install --patch -f 2.4.2`

error:
```
Inspect or clean up the working tree at /var/folders/99/8h26v_fs6d76rfhsyxkj89hw7807y2/T/ruby-build.20190830111832.57168
Results logged to /var/folders/99/8h26v_fs6d76rfhsyxkj89hw7807y2/T/ruby-build.20190830111832.57168.log

Last 10 log lines:
...
make: ./config.status: Permission denied
```

The file it will fail on with permissions can vary but this was my fix:
```
cd
cd .rbenv/versions/
mkdir 2.4.2
mkdir 2.4.2/lib
cd /var/folders/99/8h26v_fs6d76rfhsyxkj89hw7807y2/T/ruby-build.20190830111832.57168/ruby-2.4.2
make install
```

**Comment by akac** [comment] 2019-10-07 17:10
`make install` works - but if I do that it does not link to homebrew's openSSL. How do we make sure make install uses homebrew's openSSL

**Comment by vrcca** [comment] 2019-11-20 17:13
Same problem here on MacOS 10.15.1. However there were some tricks for `asdf`: 

I solved the problem doing the `cd` plus `make install`. However, I am using `asdf` to manage my environment, and I needed to do a few things to make `asdf` work properly.

Before running `make install`, ensure that the following folders and links (change the version) are created:

```
mkdir -p ~/.asdf/installs/ruby/2.5.6/bin
mkdir -p ~/.asdf/installs/ruby/2.5.6/lib
mkdir -p ~/.asdf/installs/ruby/2.5.6/include 
ln -s /var/folders/path/to/ruby-build/openssl-1.1.1b ~/.asdf/installs/ruby/2.5.6/openssl
```

Now you can run `make install`. After the installation completes, set the ruby version in `asdf`. I needed to `asdf reshim` in order to asdf to be able to see it.

**Comment by shanepinnell** [comment] 2020-12-16 00:38
Same issue on MacOS 11. cd into working directory and make install fixes it.

**Comment by AlaaAttya** [comment] 2020-12-27 15:06
Dec. 2019 and still happening!

**Comment by vinayaksakhare** [comment] 2021-05-06 23:16
Finally Got it working !!
Go to `.rvm/src/ruby-x.x.x` and run `make install`

**Comment by alejandromangione** [comment] 2022-03-16 23:40
Same issue on Mac OS Monterey 12.2.1, and I fixed navigating to the temp folder and running `make install`
