### ISSUE TITLE
Ruby 2.5.0-preview1 fails to build on macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by svoboda-jan** [rbenv/ruby-build#1139] opened 2017-10-13 21:07 UTC
```
$ xcode-select -p

/Applications/Xcode.app/Contents/Developer
```

```
$ gcc -v

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ rbenv install 2.5.0-preview1

Downloading openssl-1.1.0f.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/12f746f3f2493b2f39da7ecf63d7ee19c6ac9ec6a4fcd8c229da8a522cb12765
Installing openssl-1.1.0f...
Installed openssl-1.1.0f to /Users/username/.rbenv/versions/2.5.0-preview1

Downloading ruby-2.5.0-preview1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.0-preview1.tar.bz2
Installing ruby-2.5.0-preview1...

BUILD FAILED (OS X 10.13 using ruby-build 20170914-5-gf41e847)

Inspect or clean up the working tree at /var/folders/k0/txdvcgj145v2d3lb358bnkkr0000gn/T/ruby-build.20171013221528.17242
Results logged to /var/folders/k0/txdvcgj145v2d3lb358bnkkr0000gn/T/ruby-build.20171013221528.17242.log

Last 10 log lines:
    X509_REQ_get0_signature(req, NULL, &alg);
    ^
5 warnings generated.
4 warnings generated.
1 warning generated.
8 warnings generated.
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
linking shared-object ripper.bundle
make: *** [build-ext] Error 2
```

```
ossl_x509cert.c:87:5: warning: implicit declaration of function 'X509_up_ref' is invalid in C99 [-Wimplicit-function-declaration]
    X509_up_ref(x509);
    ^
ossl_x509cert.c:334:31: warning: implicit declaration of function 'X509_get0_tbs_sigalg' is invalid in C99 [-Wimplicit-function-declaration]
    if (!i2a_ASN1_OBJECT(out, X509_get0_tbs_sigalg(x509)->algorithm)) {
                              ^
ossl_x509cert.c:334:59: error: member reference type 'int' is not a pointer
    if (!i2a_ASN1_OBJECT(out, X509_get0_tbs_sigalg(x509)->algorithm)) {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
ossl_x509cert.c:424:22: warning: implicit declaration of function 'X509_get0_notBefore' is invalid in C99 [-Wimplicit-function-declaration]
    if (!(asn1time = X509_get0_notBefore(x509))) {
                     ^
ossl_x509cert.c:424:20: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
    if (!(asn1time = X509_get0_notBefore(x509))) {
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_x509cert.c:463:22: warning: implicit declaration of function 'X509_get0_notAfter' is invalid in C99 [-Wimplicit-function-declaration]
    if (!(asn1time = X509_get0_notAfter(x509))) {
                     ^
ossl_x509cert.c:463:20: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
    if (!(asn1time = X509_get0_notAfter(x509))) {
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings and 1 error generated.
make[2]: *** [ossl_x509cert.o] Error 1
make[2]: *** Waiting for unfinished jobs....
ossl_x509crl.c:175:5: warning: implicit declaration of function 'X509_CRL_get0_signature' is invalid in C99 [-Wimplicit-function-declaration]
    X509_CRL_get0_signature(crl, NULL, &alg);
    ^
ossl_x509crl.c:214:12: warning: implicit declaration of function 'X509_CRL_get0_lastUpdate' is invalid in C99 [-Wimplicit-function-declaration]
    time = X509_CRL_get0_lastUpdate(crl);
           ^
ossl_x509crl.c:214:10: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
    time = X509_CRL_get0_lastUpdate(crl);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_x509crl.c:245:12: warning: implicit declaration of function 'X509_CRL_get0_nextUpdate' is invalid in C99 [-Wimplicit-function-declaration]
    time = X509_CRL_get0_nextUpdate(crl);
           ^
ossl_x509crl.c:245:10: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
    time = X509_CRL_get0_nextUpdate(crl);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_x509revoked.c:134:31: warning: implicit declaration of function 'X509_REVOKED_get0_serialNumber' is invalid in C99 [-Wimplicit-function-declaration]
    return asn1integer_to_num(X509_REVOKED_get0_serialNumber(rev));
                              ^
ossl_x509revoked.c:134:31: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const ASN1_INTEGER *' (aka 'const struct asn1_string_st *') [-Wint-conversion]
    return asn1integer_to_num(X509_REVOKED_get0_serialNumber(rev));
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./ossl_asn1.h:31:46: note: passing argument to parameter here
VALUE asn1integer_to_num(const ASN1_INTEGER *);
                                             ^
ossl_x509revoked.c:161:12: warning: implicit declaration of function 'X509_REVOKED_get0_revocationDate' is invalid in C99 [-Wimplicit-function-declaration]
    time = X509_REVOKED_get0_revocationDate(rev);
           ^
ossl_x509req.c:ossl_x509revoked.c:161:10: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
266:5:    time = X509_REVOKED_get0_revocationDate(rev);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 warning: implicit declaration of function 'X509_REQ_get0_signature' is invalid in C99 [-Wimplicit-function-declaration]
    X509_REQ_get0_signature(req, NULL, &alg);
    ^
5 warnings generated.
4 warnings generated.
1 warning generated.
8 warnings generated.
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
linking shared-object ripper.bundle
make: *** [build-ext] Error 2
```

**Comment by hsbt** [comment] 2017-10-21 03:10
Thanks to your report.

But I couldn't reproduce this.

```
~ > rbenv install 2.5.0-preview1 
Installing openssl-1.1.0f...
Installed openssl-1.1.0f to /Users/hsbt/.rbenv/versions/2.5.0-preview1

Installing ruby-2.5.0-preview1...
ruby-build: use readline from homebrew
Installed ruby-2.5.0-preview1 to /Users/hsbt/.rbenv/versions/2.5.0-preview1

~ > otool -L /Users/hsbt/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle 
/Users/hsbt/.rbenv/versions/2.5.0-preview1/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle:
	/Users/hsbt/.rbenv/versions/2.5.0-preview1/openssl/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/Users/hsbt/.rbenv/versions/2.5.0-preview1/openssl/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

It seems to work with standalone openssl libraries.

**Comment by svoboda-jan** [comment] 2017-10-21 10:56
Are you using the same gcc version?

**Comment by anikolaev94** [comment] 2017-12-13 11:57
Hi! When trying to install 2.5.0-preview1, I get this

    myuser$ rbenv install 2.5.0-preview1
    ruby-build: definition not found: 2.5.0-preview1

    See all available versions with `rbenv install --list'.

    If the version you need is missing, try upgrading ruby-build:

     brew update && brew upgrade ruby-build

Then I try to upgrade ruby-build:

    myuser$ brew update && brew upgrade ruby-build
    Already up-to-date.
    Error: ruby-build 20170914 already installed

**Comment by Petercopter** [comment] 2017-12-14 18:04
Same here. `rbenv install --list` results in (abbreviated)
```
  ...
  2.4.0
  2.4.1
  2.4.2
  2.5.0-dev
  jruby-1.5.6
  jruby-1.6.3
  jruby-1.6.4
  ...
```

**Comment by hsbt** [comment] 2017-12-15 01:00
@anikolaev94 @Petercopter I send a new version to homebrew. https://github.com/Homebrew/homebrew-core/pull/21736

Please try it again after merged.

**Closed** 2018-01-04 20:21 UTC

**Comment by keithrbennett** [comment] 2018-01-09 05:17
I am having this issue trying to build Ruby 2.5.0 using `rvm`.

**Comment by leei** [comment] 2018-01-20 00:37
I'm having the same problem with 2.5.0 released on OSX  

```
% gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
produces the following:
```
compiling ossl_x509attr.c
compiling ossl_x509cert.c
ossl_x509cert.c:87:5: warning: implicit declaration of function 'X509_up_ref' is invalid in C99 [-Wimplicit-function-declaration]
    X509_up_ref(x509);
    ^
ossl_x509cert.c:334:31: warning: implicit declaration of function 'X509_get0_tbs_sigalg' is invalid in C99 [-Wimplicit-function-declaration]
    if (!i2a_ASN1_OBJECT(out, X509_get0_tbs_sigalg(x509)->algorithm)) {
                              ^
ossl_x509cert.c:334:59: error: member reference type 'int' is not a pointer
    if (!i2a_ASN1_OBJECT(out, X509_get0_tbs_sigalg(x509)->algorithm)) {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
ossl_x509cert.c:424:22: warning: implicit declaration of function 'X509_get0_notBefore' is invalid in C99 [-Wimplicit-function-declaration]
    if (!(asn1time = X509_get0_notBefore(x509))) {
                     ^
ossl_x509cert.c:424:20: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
    if (!(asn1time = X509_get0_notBefore(x509))) {
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_x509cert.c:443:10: warning: implicit declaration of function 'X509_set1_notBefore' is invalid in C99 [-Wimplicit-function-declaration]
    if (!X509_set1_notBefore(x509, asn1time)) {
         ^
ossl_x509cert.c:463:22: warning: implicit declaration of function 'X509_get0_notAfter' is invalid in C99 [-Wimplicit-function-declaration]
    if (!(asn1time = X509_get0_notAfter(x509))) {
                     ^
ossl_x509cert.c:463:20: warning: incompatible integer to pointer conversion assigning to 'const ASN1_TIME *' (aka 'const struct asn1_string_st *') from 'int' [-Wint-conversion]
    if (!(asn1time = X509_get0_notAfter(x509))) {
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~~
ossl_x509cert.c:482:10: warning: implicit declaration of function 'X509_set1_notAfter' is invalid in C99 [-Wimplicit-function-declaration]
    if (!X509_set1_notAfter(x509, asn1time)) {
         ^
8 warnings and 1 error generated.
make[2]: *** [ossl_x509cert.o] Error 1
make[1]: *** [ext/openssl/all] Error 2
make: *** [build-ext] Error 2
```

**Comment by keithrbennett** [comment] 2018-01-20 04:27
I was able to solve the problem in `rvm` using its `--with-openssl` option pointed to my `brew` version of `openssl` (`/usr/local/opt/openssl` I believe) rather than the OS' version. Is there some option like that for `rbenv`?

**Comment by svoboda-jan** [comment] 2018-01-20 17:02
`rbenv` compiles its own version of compatible OpenSSL.

Some pacakge managers like MacPorts can confuse rbenv.

With MacPorts I was able to install `2.5.0` after cleaning the `PATH` variable from MacPorts with:

```bash
$ export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.rbenv/bin
```

**Please note that this is intended only as a workaround for the mentioned OpenSSL error and only to complete the installation, after that MacPorts or other package manager is needed to install various dependencies for gems, so the `PATH` variable shoud be reset to original value by closing and reopening the terminal application after installing ruby.**

**Comment by Sija** [comment] 2018-03-29 12:11
@keithrbennett correct option name is `--with-openssl-dir`.

**Comment by kixarinum** [comment] 2018-06-07 12:22
This also worked for me:

```bash
rvm install 2.5.1 --disable-binary  --with-openssl-dir=/usr/local/Cellar/openssl/
```

**Comment by FrankFang** [comment] 2018-08-02 14:40
https://github.com/rvm/rvm/issues/4271#issuecomment-354952009

**Comment by pjbelo** [comment] 2018-10-13 21:04
Hi. Similar problem. Solved with:
```
rvm install ruby-2.5.1 --with-openssl-dir=/usr/local/opt/openssl
```
You can also check if XCode is updated

**Comment by joshuapinter** [comment] 2019-10-27 01:25
For rbenv you can use the `RUBY_CONFIGURE_OPTS` environment variable to pass in `--with-openssl-dir`, like: 

```bash
RUBY_CONFIGURE_OPTS=--with-openssl-dir=/usr/local/opt/openssl rbenv install ruby-2.5.1
```

**Comment by sam0x17** [comment] 2019-11-13 01:43
best way seems to be:

```
brew install openssl
rvm install 2.5.0 --with-openssl-dir=`brew --prefix openssl`
```

**Comment by keithrbennett** [comment] 2020-02-19 18:02
I commented previously that the `--with-openssl-dir=$(brew --prefix openssl)` would fix the problem, but today I tried to install Ruby 2.7.0 with rvm and it failed. What fixed it was, I did a `brew info openssl` to get some clues, and this worked:

`export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"`

Your directory may differ, it was in the output of `brew info openssl`, but that export fixed the problem for me.
