### ISSUE TITLE
Ruby 2.1.0 libyaml not functional without setting LD_LIBARY_PATH on FreeBSD

### ISSUE THREAD

**Issue by p-originate** [rbenv/ruby-build#509] opened 2014-02-15 03:53 UTC
<pre>
stealth% rbenv install 2.1.0
Downloading yaml-0.1.5.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/24f6093c1e840ca5df2eb09291a1dbf1
Installing yaml-0.1.5...
Installed yaml-0.1.5 to /home/me/.rbenv/versions/2.1.0

Downloading ruby-2.1.0.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/9e6386d53f5200a3e7069107405b93f7
Installing ruby-2.1.0...
Installed ruby-2.1.0 to /home/me/.rbenv/versions/2.1.0
</pre>

Ok. Now let's try:

<pre>
stealth% gem install rails
/home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': Shared object "libyaml-0.so.2" not found, required by "psych.so" - /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/x86_64-freebsd9.1/psych.so (LoadError)
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/psych.rb:1:in `<top (required)>'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/yaml.rb:5:in `<top (required)>'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems.rb:616:in `load_yaml'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/config_file.rb:327:in `load_file'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/config_file.rb:196:in `initialize'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/gem_runner.rb:74:in `new'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/gem_runner.rb:74:in `do_configuration'
    from /home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/rubygems/gem_runner.rb:39:in `run'
    from /home/me/.rbenv/versions/2.1.0/bin/gem:21:in `<main>'
</pre>

Hmm. Where is it?

<pre>
stealth% find /home/me/.rbenv/versions/2.1.0 |grep libyaml
/home/me/.rbenv/versions/2.1.0/lib/libyaml-0.so.2
/home/me/.rbenv/versions/2.1.0/lib/libyaml-0.so
/home/me/.rbenv/versions/2.1.0/lib/libyaml.so
/home/me/.rbenv/versions/2.1.0/lib/libyaml.la
/home/me/.rbenv/versions/2.1.0/lib/libyaml.a
</pre>

Same place as in 2.0.0 which works fine:

<pre>
stealth% find ~/.rbenv |grep libyaml
/home/me/.rbenv/versions/1.9.3-p194/lib/libyaml-0.so.2
/home/me/.rbenv/versions/1.9.3-p194/lib/libyaml-0.so
/home/me/.rbenv/versions/1.9.3-p194/lib/libyaml.so
/home/me/.rbenv/versions/1.9.3-p194/lib/libyaml.la
/home/me/.rbenv/versions/1.9.3-p194/lib/libyaml.a
/home/me/.rbenv/versions/1.9.3-p194/share/ri/1.9.1/system/Psych/libyaml_version-c.ri
/home/me/.rbenv/versions/2.0.0-p0/share/ri/2.0.0/system/Psych/libyaml_version-c.ri
/home/me/.rbenv/versions/2.1.0/lib/libyaml-0.so.2
/home/me/.rbenv/versions/2.1.0/lib/libyaml-0.so
/home/me/.rbenv/versions/2.1.0/lib/libyaml.so
/home/me/.rbenv/versions/2.1.0/lib/libyaml.la
/home/me/.rbenv/versions/2.1.0/lib/libyaml.a
/home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/x86_64-freebsd9.1/libyaml-0.so.2
/home/me/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/x86_64-freebsd9.1/libyaml-0.so.2
/home/me/.rbenv/versions/2.1.0/share/ri/2.1.0/system/Psych/libyaml_version-c.ri
</pre>

I tried hardlinking libyaml-0.so.2 to a couple of places like `/home/me/.rbenv/versions/2.1.0/lib/ruby/2.1.0/x86_64-freebsd9.1` and `/home/me/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/x86_64-freebsd9.1` but that had no effect.

<pre>
stealth% uname -a                                                                                                                      
FreeBSD stealth.here 9.1-RELEASE FreeBSD 9.1-RELEASE #0 r243825: Tue Dec  4 09:23:10 UTC 2012     root@farrell.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64
</pre>

**Comment by hsbt** [comment] 2017-08-29 04:50
I will close this.

I couldn't reproduce FreeBSD 11.0 and Ruby 2.1.10.

**Closed by hsbt** 2017-08-29 04:50 UTC
Labels: x-platform
