### ISSUE TITLE
How do we get actually ruby-build issues and not tons of noise?

### ISSUE THREAD

**Issue by eregon** [rbenv/ruby-build#2084] opened 2022-11-07 15:25 UTC
cc @mislav @hsbt
I'm getting really tired of people reporting so many build issues of CRuby on ruby-build's tracker, e.g., https://github.com/rbenv/ruby-build/discussions/2083#discussioncomment-4077248
I'm happy to help maintaining ruby-build, I'm not happy to get notified about people messing up their build environment and potential issues with building CRuby itself, which cannot be fixed in ruby-build.
I just don't have to time to debug people messing their environment or to debug CRuby/openssl problems and it is not my responsibility.

I see we already have issue templates but they don't seem enough.
Maybe we can try Issue Form templates like [here](https://github.com/ruby/setup-ruby/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) to try to ensure only ruby-build issues are actually filed here, and disable blank issues?
Maybe we should ask for a Dockerfile reproducing the issue for Linux?
Or give a list of commands to build ruby from source manually and tell people to try that and only file an issue if that works but ruby-build doesn't? (otherwise use discussions or link to https://bugs.ruby-lang.org/)

Short-term I will simply stop watching issues for this repository, so people will need to ping me if they need me.

**Comment by mislav** [comment] 2022-11-07 16:01
In https://github.com/rbenv/ruby-build/issues/new/choose we already direct people to Discussions area for their BUILD FAILED problems. But the person you quoted has specifically opened an issue because they believed that this is a ruby-build bug.

I do not know how to solve this. This project is people's window into installing Ruby on their machine and every problem with that installation can be potentially perceived as a ruby-build problem. Most people do not have understanding of what our tool does and does not do and I can't blame them.

**Comment by eregon** [comment] 2022-11-07 17:28
> Most people do not have understanding of what our tool does and does not do and I can't blame them.

Maybe we need to explain that better in the README and/or the issue template then.
Or even in the output during installation.
It's pretty simple overall, and any compilation failure is almost never ruby-build's issue.

Or, tell people to report an issue only if they can't repro with simple manual instructions.

**Comment by mislav** [comment] 2022-11-07 18:28
I like your idea with printing instructions such as `./configure && make && make install` and asking people to run those in a checkout of Ruby source code to try to reproduce the issue. If building succeeds, then it could be ruby-build's fault for messing up an installation.

I wonder what would be an easy way of having ruby-build report those instructions. I'd like a no-op mode where ruby-build only _prints_ what would be executed but doesn't actually run it 🤔

**Comment by jqr** [comment] 2023-02-09 15:15
Would it make sense to detect a build failure and print the recommended next steps(above) and which specifically call out where to open issues? Something like:

```ruby
if error
  puts "*** ERROR: Build failed with the following error:"
  puts error.lines.first(3).join("\n")
  puts "Full error: #{error_log}"
  puts 
  puts "Since you're building #{installation.name}, you should check its issue tracker for help:"
  puts installation.issue_url
end
```

**Comment by mislav** [comment] 2023-03-06 18:41
Closing in order to clean the issue backlog and because I'm not sure of an immediately actionable solution to all this. 

Being able to communicate to users that they should try downloading, extracting, and manually building Ruby could definitely rule out bugs specific to this project, but is a large ask that I wouldn't be comfortable making of most users unless ruby-build could _generate precise manual instructions_ and print them for our users who suffered a build failure. 

Furthermore, it looks like there were very few BUILD FAILED reports in the issue tracker and that most people are posting in Discussions instead, which is what we want.

@eregon: feel free to unsubscribe from new issues in this repo. I could @-mention you on anything that could specifically need your attention. 🙇

**Closed by mislav** 2023-03-06 18:41 UTC

**Comment by eregon** [comment] 2023-03-06 19:16
Yeah that's fine. I did  unsubscribe from new issues in this repo, I'm currently still watching PRs, that's more manageable.

**Comment by jasonkarns** [comment] 2023-03-07 04:39
I wonder if we could use the Issue template to also suggest running `rbenv-doctor`?

Homebrew usually makes it a pre-req for having "clean" doctor output before accepting issues. There's a chance that pointing more people to rbenv-doctor might help self-serve minor configuration issues? Though I believe the current rbenv-doctor checks are more suited to rbenv itself than ruby-build.

**Comment by mislav** [comment] 2023-03-07 16:03
@jasonkarns Yes, rbenv-doctor currently isn't very useful for Ruby build problems. I imagine that a better doctor command would print extra information about your build environment (including architecture, compiler versions, and relevant environment variables), as well as check for suggested build environment (as per our wiki). Ideally, it would also be built into ruby-build. Should we prioritize this?

**Comment by jasonkarns** [comment] 2023-03-08 03:18
@mislav on one hand, I'd like to think that more self-help  diagnostic tooling could cut help cut down on volume. But otoh, I'm a bit skeptical that it would cause a dramatic difference. Hence why the existing rbenv doctor seemed like a worthwhile (somewhat minimal) effort to layer in somehow.

But more involved effort in creating a new tool would require a higher expected payoff to be worth it?

And I'll be honest that the actual compilation of ruby is where I'm least comfortable/helpful so don't want to volunteer any extra work on others 😅
