### ISSUE TITLE
Installing Ruby 3.2.2 on FreeBSD fails due to missing libyaml even when it is installed

### ISSUE THREAD

**Issue by jarmo** [rbenv/ruby-build#2184] opened 2023-04-09 12:30 UTC
### Steps to reproduce the behavior

When trying to install Ruby 3.2.2 on FreeBSD then it fails by complaining that `libyaml` is missing even though it is installed. Passing `--with-libyaml-dir` fixes it. Similar problem with `libffi`.

More discussion and problem description available at https://github.com/rbenv/ruby-build/discussions/2168#discussioncomment-5563978

### Expected vs. actual behavior

Ruby 3.2.2 should be installed successfully when `libyaml` and `libffi` are installed.

**Comment by hsbt** [comment] 2023-04-10 05:44
Do you know why FreeBSD refuse to add `/usr/local` for searching headers and libraries paths?

**Comment by jarmo** [comment] 2023-04-10 07:49
@hsbt not sure, but I do know that building older versions of Ruby (3.2.1 for example and 2.7.x) work fine without any `RUBY_CONFIGURE_OPTS` changes.

I don't know almost anything about `ruby-build` internals, but it's also hard to believe that these are only system dependencies, which are required to build Ruby. Or are `libyaml` and `libffi` something new to the Ruby 3.2.2 and it was working somehow differently before?

**Comment by hsbt** [comment] 2023-04-12 01:47
There is no change between Ruby 3.2.1 and 3.2.2 related libyaml.

**Comment by mislav** [comment] 2023-04-13 12:42
@jarmo Does the same problem happen if you try to manually download and extract the Ruby 3.2.2 tarball, cd into it, and run `./configure --prefix /tmp/ruby3.2.2 --disable-install-doc` followed by `make` and `make install` there?

**Comment by jarmo** [comment] 2023-04-13 17:34
@mislav `configure` and `make` are successful, but `make install` fails:
```
...
linking static-library libruby-static.a
merging yjit/target/release/libyjit.a into libruby-static.a
linking ruby
*** Following extensions are not compiled:
fiddle:
        Could not be configured. It will not be installed.
        /root/ruby-3.2.2/ext/fiddle/extconf.rb:73: missing libffi. Please install libffi or use --with-libffi-source-dir with libffi source location.
        Check ext/fiddle/mkmf.log for more details.
psych:
        Could not be configured. It will not be installed.
        Check ext/psych/mkmf.log for more details.
readline:
        Could not be configured. It will not be installed.
        /root/ruby-3.2.2/ext/readline/extconf.rb:62: Neither readline nor libedit was found
        Check ext/readline/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.
making enc
`enc' is up to date.
making trans
`trans' is up to date.
making encs
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-freebsd13.1-fake ./tool/rbinstall.rb --make="make" --dest-dir=""  --extout=".ext"  --ext-build-dir="./ext"  --mflags=" "  --make-flags=" "  --data-mode=0644  --prog-mode=0755  --installed-list .installed.list  --mantype="doc"   --install=all --exclude=doc
installing binary commands:         /tmp/ruby3.2.2/bin
installing base libraries:          /tmp/ruby3.2.2/lib
installing arch files:              /tmp/ruby3.2.2/lib/ruby/3.2.0/x86_64-freebsd13.1
installing pkgconfig data:          /tmp/ruby3.2.2/lib/pkgconfig
installing extension objects:       /tmp/ruby3.2.2/lib/ruby/3.2.0/x86_64-freebsd13.1
installing extension objects:       /tmp/ruby3.2.2/lib/ruby/site_ruby/3.2.0/x86_64-freebsd13.1
installing extension objects:       /tmp/ruby3.2.2/lib/ruby/vendor_ruby/3.2.0/x86_64-freebsd13.1
installing extension headers:       /tmp/ruby3.2.2/include/ruby-3.2.0/x86_64-freebsd13.1
installing extension scripts:       /tmp/ruby3.2.2/lib/ruby/3.2.0
installing extension scripts:       /tmp/ruby3.2.2/lib/ruby/site_ruby/3.2.0
installing extension scripts:       /tmp/ruby3.2.2/lib/ruby/vendor_ruby/3.2.0
installing extension headers:       /tmp/ruby3.2.2/include/ruby-3.2.0/ruby
installing command scripts:         /tmp/ruby3.2.2/bin
installing library scripts:         /tmp/ruby3.2.2/lib/ruby/3.2.0
installing common headers:          /tmp/ruby3.2.2/include/ruby-3.2.0
installing manpages:                /tmp/ruby3.2.2/share/man/man1
installing default gems from lib:   /tmp/ruby3.2.2/lib/ruby/gems/3.2.0
                                    abbrev 0.1.1
                                    base64 0.1.1
                                    benchmark 0.2.1
                                    bundler 2.4.10
<internal:/root/ruby-3.2.2/lib/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- psych (LoadError)
        from <internal:/root/ruby-3.2.2/lib/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /root/ruby-3.2.2/lib/rubygems.rb:608:in `load_yaml'
        from /root/ruby-3.2.2/lib/rubygems/config_file.rb:346:in `load_file'
        from /root/ruby-3.2.2/lib/rubygems/config_file.rb:189:in `initialize'
        from /root/ruby-3.2.2/lib/rubygems.rb:329:in `new'
        from /root/ruby-3.2.2/lib/rubygems.rb:329:in `configuration'
        from /root/ruby-3.2.2/lib/rubygems/user_interaction.rb:167:in `verbose'
        from /root/ruby-3.2.2/lib/rubygems/installer.rb:544:in `generate_bin_script'
        from ./tool/rbinstall.rb:891:in `generate_bin_script'
        from ./tool/rbinstall.rb:855:in `generate_bin_script'
        from /root/ruby-3.2.2/lib/rubygems/installer.rb:506:in `block in generate_bin'
        from /root/ruby-3.2.2/lib/rubygems/installer.rb:490:in `each'
        from /root/ruby-3.2.2/lib/rubygems/installer.rb:490:in `generate_bin'
        from /root/ruby-3.2.2/lib/rubygems/installer.rb:331:in `install'
        from ./tool/rbinstall.rb:881:in `block in install'
        from ./tool/rbinstall.rb:721:in `no_write'
        from ./tool/rbinstall.rb:881:in `install'
        from ./tool/rbinstall.rb:989:in `block in install_default_gem'
        from ./tool/rbinstall.rb:976:in `each'
        from ./tool/rbinstall.rb:976:in `install_default_gem'
        from ./tool/rbinstall.rb:913:in `block in <main>'
        from ./tool/rbinstall.rb:1080:in `block in <main>'
        from ./tool/rbinstall.rb:1077:in `each'
        from ./tool/rbinstall.rb:1077:in `<main>'
*** Error code 1

Stop.
make: stopped in /root/ruby-3.2.2
```

As is shown then `fiddle`, `psych` and `readline` fail to be compiled. Looking into `ext/psych/mkmf.log` it is visible, that `yaml.h` is not found:
```
package configuration for yaml-0.1 is not found
find_header: checking for yaml.h... -------------------- no

LD_LIBRARY_PATH=.:../.. "clang -o conftest -I../../.ext/include/x86_64-freebsd13.1 -I../.././include -I../.././ext/psych    -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wundef conftest.c  -L. -L../.. -L. -fstack-protector-strong -rdynamic     -Wl,-rpath,/tmp/ruby3.2.2/lib -L/tmp/ruby3.2.2/lib -lruby-static -lexecinfo -lprocstat -lz -lrt -lrt -ldl -lcrypt -lm -lthr   -lm -lthr  -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

LD_LIBRARY_PATH=.:../.. "clang -I../../.ext/include/x86_64-freebsd13.1 -I../.././include -I../.././ext/psych    -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wundef   -c conftest.c"
conftest.c:3:10: fatal error: 'yaml.h' file not found
#include <yaml.h>
         ^~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <yaml.h>
/* end */
--------------------
```

Of course `libffi` is installed:
```
# pkg info libffi
libffi-3.4.4
Name           : libffi
Version        : 3.4.4
Installed on   : Sun Apr  9 22:46:08 2023 EEST
Origin         : devel/libffi
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : devel
```

And `readline`:
```
# pkg info readline
readline-8.2.0
Name           : readline
Version        : 8.2.0
Installed on   : Sun Apr  9 21:47:31 2023 EEST
Origin         : devel/readline
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : devel
```

And `libyaml`:
```
# pkg info libyaml
libyaml-0.2.5
Name           : libyaml
Version        : 0.2.5
Installed on   : Sun Apr  9 22:45:06 2023 EEST
Origin         : textproc/libyaml
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : textproc
```

I tried same commands with Ruby 3.2.1 and failed exactly the same. Same results with 3.2.0.

So I tried same commands with 3.1.2 and everything worked. I see that I've mentioned above Ruby 3.2.1, but I start to suspect that it was 3.1.2 all the time instead. Sorry for the confusion.

**Comment by jarmo** [comment] 2023-04-13 17:55
Ruby 3.1.4 compiles too without any errors so it seems to be the 3.x versions, which fail.

**Comment by mislav** [comment] 2023-04-14 13:44
@jarmo Thanks for the info! It sounds like a regression in the build system for Ruby 3.2 on FreeBSD.

Does something like this work? If so, we could consider adding these defaults to ruby-build until this is fixed in Ruby upstream:
```sh
./configure --prefix /tmp/ruby-3.2.1 --with-libyaml-dir=/usr/local --with-libffi-dir=/usr/local --with-readline-dir=/usr/local
```
Or, alternatively, maybe amending LDFLAGS & CPPFLAGS would help?
```sh
export LDFLAGS=-L/usr/local/lib
export CPPFLAGS=-I/usr/local/include
./configure --prefix /tmp/ruby-3.2.1
make && make install
```

**Comment by jarmo** [comment] 2023-04-14 19:18
@mislav thank you for hinting to that PR

I create a PR based on that information, which fixes building/installing Ruby 3.2.x on FreeBSD https://github.com/rbenv/ruby-build/pull/2187

**Comment by jarmo** [comment] 2023-04-24 19:28
@mislav I guess this can be closed now or does it need to be kept open until new version of `ruby-build` has been released somehow?

**Comment by mislav** [comment] 2023-04-24 19:36
Fixed in https://github.com/rbenv/ruby-build/commit/b80e686b6ee6a29bd7b391f4c54ddce3bd437de4

**Closed by mislav** 2023-04-24 19:36 UTC
Labels: bug

**Comment by kevinhq** [comment] 2025-02-05 11:43
this is happening on debian 12 as well.

**Comment by npgretz** [comment] 2025-02-08 14:15
I got this same issue on Almalinux9 trying to install 3.4.1 and 3.4.0. I then gave up and switched to RVM which promptly installed libffi-devel. I had already confirmed that libffi was installed and I used --with-libffi-source-dir=/usr/lib64/libffi.so.8.1.0. Looks like libffi-devel also needs to be installed though.

**Comment by SpBills** [comment] 2025-03-10 12:06
For those on Debian/Ubuntu:

```
sudo apt install libffi-dev
sudo apt install libyaml-dev
```

CC: @kevinhq
