### ISSUE TITLE
On Mac Sierra Beta, rbenv install 2.4.0 hangs at "use realline from homebrew"

### ISSUE THREAD

**Issue by pitosalas** [rbenv/ruby-build#1064] opened 2017-03-14 15:38 UTC
```
rbenv install 2.4.0
ruby-build: use openssl from homebrew
Downloading ruby-2.4.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.bz2
Installing ruby-2.4.0...
ruby-build: use readline from homebrew

... at which point I hang
```
I googled like crazy, reinstalled new brew versions of readline, openssl libyaml and libffi. Any ideas?

**Comment by small-fish** [comment] 2017-03-17 16:45
I had the same problem. It was resolved by reinstalling rbenv

**Comment by lowderl** [comment] 2017-03-20 14:48
Also having this problem. Reinstalling rbenv did not fix it for me.
Tried reinstalling lots of stuff, and ran brew update && brew doctor.

**Comment by small-fish** [comment] 2017-03-20 14:55
If you used to use rvm, make sure that you removed it completely.

**Comment by ahalls** [comment] 2017-03-28 01:02
Patience

**Comment by lowderl** [comment] 2017-03-28 02:12
This fixed it for me:
```bash
RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 2.4.0
```

**Comment by MarkehMe** [comment] 2017-04-02 05:28
@lowderl You have made my day, hour wasted - IOU a beer!

**Comment by ricardomeza** [comment] 2017-06-25 17:14
This works for me too, tks @lowderl !

**Comment by mislav** [comment] 2017-06-26 09:08
Thanks for sharing the workaround, @lowderl.

It's strange that this step should fix the installation because `--with-readline-dir="$(brew --prefix readline)"` is basically identical to what the "use readline from homebrew" step does.

I don't run macOS beta so I can't look into this yet, but if anyone is willing to look more closely into this, I would be grateful. Two things could be of use:

* Tailing the log at the time of the process being stuck: `tail -f "$(ls -t $TMPDIR/ruby-build.*.log | head -1)"` in another tab;
* Enabling bash verbose mode by adding `set -x` to the beginning of `ruby-build` executable.

**Comment by paniclater** [comment] 2017-07-05 17:08
I thought I was having this problem, but I tailed the logs and cannot reproduce the issue. I think that it just takes a long time to install and without the output feedback I was assuming it was hanging.

**Comment by ProtectedVoid** [comment] 2017-07-13 13:48
@paniclater I encountered the same thing.  Without feedback, it does appear to hang, but after about 3-4 minutes, the install completes successfully.

**Comment by skirdey** [comment] 2017-08-16 00:29
Had to wait a few minutes, it worked.

**Comment by murnun** [comment] 2017-08-25 23:54
Same. Just had to give it few more mins...

**Comment by mgadda** [comment] 2017-09-19 23:04
While we're collecting data: I gave it several hours. It did not work.

**Comment by billfienberg** [comment] 2017-10-19 12:20
It took several minutes for me, but it did eventually succeed.

**Comment by orospakr** [comment] 2017-10-24 02:14
To get better visibility on what's going on in the build process, I recommend running builds with `-v`. ie.: `rbenv install -v 2.4.21`

**Comment by joemsak** [comment] 2017-11-09 16:13
Followed @orospakr's advice, running in verbose mode, and It's just taking an extremely long time for me.

Will follow up about whether it finishes successfully.

**Comment by pierremanceaux** [comment] 2017-11-13 13:36
Approx. 6 mins for me on a 2014 MBP on High Sierra, worked all fine.

**Comment by manideep0000** [comment] 2018-01-25 21:54
It works before, But not Now. tried reinstalling brew, rbenv and deleting /usr/local/lib/ruby directory and redoing the whole things but still no luck..Any idea i get this 
`rbenv install 2.4.0
ruby-build: use openssl from homebrew
Downloading ruby-2.4.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.bz2
Installing ruby-2.4.0...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.13.2 using ruby-build 20171226)

Inspect or clean up the working tree at /var/folders/vz/2x71lgj94q33wmcv4pkp44gm0000gn/T/ruby-build.20180125154716.85814
Results logged to /var/folders/vz/2x71lgj94q33wmcv4pkp44gm0000gn/T/ruby-build.20180125154716.85814.log

Last 10 log lines:
The Ruby yaml extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/name/.rbenv/versions/2.4.0
  --with-openssl-dir=/usr/local/opt/openssl
  --with-readline-dir=/usr/local/opt/readline
  CC=clang
  CFLAGS= -O3 -Wno-error=shorten-64-to-32 
  LDFLAGS=-L/Users/name/.rbenv/versions/2.4.0/lib 
  CPPFLAGS=-I/Users/name/.rbenv/versions/2.4.0/include `

**Comment by MamboMaya** [comment] 2018-01-30 20:55
Took about 6-7 minutes, but it finally finished.

**Comment by davidcpell** [comment] 2018-01-31 16:46
I'm having this problem and have let installations go for ~1 hour without success. When I use `top` and `pstree` to inspect processes it says that they are "sleeping":

```
$ pstree -p 4632
-+= 00001 root /sbin/launchd
 \-+= 53577 davidpell /Applications/iTerm.app/Contents/MacOS/iTerm2
   \-+= 64148 davidpell /Applications/iTerm.app/Contents/MacOS/iTerm2 --server login -fp davidpell
     \-+= 64149 root login -fp davidpell
       \-+= 64150 davidpell /bin/zsh
         \-+= 04632 davidpell bash /Users/davidpell/.rbenv/plugins/ruby-build/bin/rbenv-install 2.4.2
           \-+- 04650 davidpell bash /Users/davidpell/.rbenv/plugins/ruby-build/bin/ruby-build 2.4.2 /Users/d
             \-+- 11180 davidpell /Applications/Xcode.app/Contents/Developer/usr/bin/make -j 8
               |--- 11188 davidpell echo translating probes probes.d
               |--- 11223 davidpell echo compiling main.c
               |--- 11230 davidpell echo compiling dmydln.c
               |--- 11237 davidpell echo compiling miniinit.c
               |--- 11244 davidpell echo compiling dmyext.c
               |--- 11251 davidpell echo compiling miniprelude.c
               |--- 11258 davidpell echo compiling bignum.c
               \--- 11265 davidpell echo compiling class.c
```

```
$ top -pid 11265
PID    COMMAND      %CPU TIME     #TH  #WQ  #POR MEM   PURG CMPR PGRP PPID  STATE    BOOSTS     %CPU_ME
11265  echo         0.0  00:00.00 5    0    17   504K  0B   0B   4632 11180 sleeping *0[1]      0.00000
```

**Comment by davidcpell** [comment] 2018-02-05 06:15
Still having this problem. @mislav Here are the logs:

```
bash-3.2$ rbenv install -v 2.2.4
ruby-build: use openssl from homebrew
/var/folders/46/bt1thz5x72311x8l3lsbq_jc0000gq/T/ruby-build.20180205010421.79706 ~
Downloading ruby-2.2.4.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.4.tar.bz2
/var/folders/46/bt1thz5x72311x8l3lsbq_jc0000gq/T/ruby-build.20180205010421.79706/ruby-2.2.4 /var/folders/46/bt1thz5x72311x8l3lsbq_jc0000gq/T/ruby-build.20180205010421.79706 ~
Installing ruby-2.2.4...

WARNING: ruby-2.2.4 is nearing its end of life.
It only receives critical security updates, no bug fixes.

config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin17.4.0
checking host system type... x86_64-apple-darwin17.4.0
checking target system type... x86_64-apple-darwin17.4.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether clang needs -traditional... no
checking for ld... ld
checking whether the linker is GNU ld... no
checking whether clang -E accepts -o... yes
checking for real target cpu... x86_64
checking for ranlib... ranlib
checking for ar... ar
checking for as... as
checking for objdump... objdump
checking for objcopy... no
checking for gobjcopy... no
checking for nm... nm
checking whether ln -s works... yes
checking whether make sets $(MAKE)... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p...  -d
use 'mkdir -p' as MKDIR_P
checking for dtrace... dtrace
checking for dot... no
checking for doxygen... no
checking for pkg-config... pkg-config
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... yes
checking whether LDFLAGS is valid... yes
checking whether -Wno-unused-parameter is accepted as CFLAGS... yes
checking whether -Wno-parentheses is accepted as CFLAGS... yes
checking whether -Wno-long-long is accepted as CFLAGS... yes
checking whether -Wno-missing-field-initializers is accepted as CFLAGS... yes
checking whether -Wunused-variable is accepted as CFLAGS... yes
checking whether -Wpointer-arith is accepted as CFLAGS... yes
checking whether -Wwrite-strings is accepted as CFLAGS... yes
checking whether -Wdeclaration-after-statement is accepted as CFLAGS... yes
checking whether -Wshorten-64-to-32 is accepted as CFLAGS... yes
checking whether -Wimplicit-function-declaration is accepted as CFLAGS... yes
checking whether -Wdivision-by-zero is accepted as CFLAGS... yes
checking whether -Wdeprecated-declarations is accepted as CFLAGS... yes
checking whether -Wno-packed-bitfield-compat is accepted as CFLAGS... no
checking whether -Wextra-tokens is accepted as CFLAGS... yes
checking whether -Wall -Wextra is accepted as CFLAGS... yes
checking whether -Qunused-arguments is accepted as CFLAGS... yes
checking whether -D_FORTIFY_SOURCE=2 is accepted as CFLAGS... yes
checking whether -fstack-protector is accepted as CFLAGS... yes
checking whether -fstack-protector is accepted as LDFLAGS... yes
checking whether -fno-strict-overflow is accepted as CFLAGS... yes
checking whether -ggdb3 is accepted as CFLAGS... yes
checking whether -fvisibility=hidden is accepted as CFLAGS... yes
checking whether -fno-fast-math is accepted as CFLAGS... yes
checking whether Mac OS X 10.5 or later... yes
checking for broken crypt with 8bit chars... no
checking for codesign... codesign
checking for crt_externs.h... yes
checking for crypt in -lcrypt... (cached) no
checking for dlopen in -ldl... yes
checking for shl_load in -ldld... no
checking for shutdown in -lsocket... no
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/fcntl.h usability... yes
checking sys/fcntl.h presence... yes
checking for sys/fcntl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking syscall.h usability... no
checking syscall.h presence... no
checking for syscall.h... no
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking a.out.h usability... no
checking a.out.h presence... no
checking for a.out.h... no
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking direct.h usability... no
checking direct.h presence... no
checking for direct.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/mkdev.h usability... no
checking sys/mkdev.h presence... no
checking for sys/mkdev.h... no
checking sys/utime.h usability... no
checking sys/utime.h presence... no
checking for sys/utime.h... no
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking ieeefp.h usability... no
checking ieeefp.h presence... no
checking for ieeefp.h... no
checking ucontext.h usability... yes
checking ucontext.h presence... yes
checking for ucontext.h... yes
checking intrinsics.h usability... no
checking intrinsics.h presence... no
checking for intrinsics.h... no
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking sys/sendfile.h usability... no
checking sys/sendfile.h presence... no
checking for sys/sendfile.h... no
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking net/socket.h usability... no
checking net/socket.h presence... no
checking for net/socket.h... no
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking process.h usability... no
checking process.h presence... no
checking for process.h... no
checking sys/prctl.h usability... no
checking sys/prctl.h presence... no
checking for sys/prctl.h... no
checking sys/uio.h usability... yes
checking sys/uio.h presence... yes
checking for sys/uio.h... yes
checking atomic.h usability... no
checking atomic.h presence... no
checking for atomic.h... no
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking malloc_np.h usability... no
checking malloc_np.h presence... no
checking for malloc_np.h... no
checking malloc/malloc.h usability... yes
checking malloc/malloc.h presence... yes
checking for malloc/malloc.h... yes
checking setjmpex.h usability... no
checking setjmpex.h presence... no
checking for setjmpex.h... no
checking sys/attr.h usability... yes
checking sys/attr.h presence... yes
checking for sys/attr.h... yes
checking sys/id.h usability... no
checking sys/id.h presence... no
checking for sys/id.h... no
checking gmp.h usability... no
checking gmp.h presence... no
checking for gmp.h... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether byte ordering is bigendian... no
checking for an ANSI C-conforming const... yes
checking whether char is unsigned... no
checking for inline... inline
checking for working volatile... yes
checking for typeof syntax and keyword spelling... typeof
checking for long long... yes
checking for off_t... yes
checking char bit... 8
checking size of int... 4
checking size of short... 2
checking size of long... 8
checking size of long long... 8
checking size of __int64... 0
checking size of __int128... 16
checking size of off_t... 8
checking size of void*... 8
checking size of float... 4
checking size of double... 8
checking size of time_t... 8
checking size of clock_t... 8
checking packed struct attribute... x __attribute__((packed))
checking for printf prefix for long long... ll
checking for pid_t... yes
checking for convertible type of pid_t... INT
checking for uid_t... yes
checking for convertible type of uid_t... UINT
checking for gid_t... yes
checking for convertible type of gid_t... UINT
checking for time_t... yes
checking for convertible type of time_t... LONG
checking for dev_t... yes
checking for convertible type of dev_t... INT
checking for mode_t... yes
checking for convertible type of mode_t... UINT
checking for rlim_t... yes
checking for convertible type of rlim_t... ULL
checking for off_t... (cached) yes
checking for convertible type of off_t... LL
checking for clockid_t... no
checking for convertible type of clockid_t... INT
checking for prototypes... yes
checking token paste string... ansi
checking stringization... #expr
checking string literal concatenation... yes
checking for variable length prototypes and stdarg.h... yes
checking for variable length macro... yes
checking for NORETURN function attribute... __attribute__ ((noreturn)) x
checking for DEPRECATED function attribute... __attribute__ ((deprecated)) x
checking for NOINLINE function attribute... __attribute__ ((noinline)) x
checking for stdcall function attribute... x
checking for cdecl function attribute... __attribute__ ((cdecl)) x
checking for fastcall function attribute... x
checking for FUNC_MINIMIZED function attribute... x
checking for function alias... no
checking for __atomic builtins... yes
checking for __sync builtins... yes
checking for __builtin_unreachable... yes
checking for exported function attribute... __attribute__ ((visibility("default")))
checking for function name string predefined identifier... __func__
checking whether sys_nerr is declared... yes
checking whether getenv is declared... yes
checking for size_t... yes
checking size of size_t... 8
checking size of ptrdiff_t... 8
checking for printf prefix for size_t... z
checking for printf prefix for ptrdiff_t... t
checking for struct stat.st_blksize... yes
checking for struct stat.st_blocks... yes
checking for struct stat.st_rdev... yes
checking size of struct stat.st_size... SIZEOF_OFF_T
checking size of struct stat.st_blocks... SIZEOF_OFF_T
checking size of struct stat.st_ino... SIZEOF_LONG
checking for struct stat.st_atim... no
checking for struct stat.st_atimespec... yes
checking for struct stat.st_atimensec... no
checking for struct stat.st_mtim... no
checking for struct stat.st_mtimespec... yes
checking for struct stat.st_mtimensec... no
checking for struct stat.st_ctim... no
checking for struct stat.st_ctimespec... yes
checking for struct stat.st_ctimensec... no
checking for struct stat.st_birthtimespec... yes
checking for struct timeval... yes
checking size of struct timeval.tv_sec... SIZEOF_TIME_T
checking for struct timespec... yes
checking for struct timezone... yes
checking for clockid_t... (cached) no
checking for fd_mask... yes
checking for int8_t... yes
checking size of int8_t... 1
checking for uint8_t... yes
checking size of uint8_t... 1
checking for int16_t... yes
checking size of int16_t... 2
checking for uint16_t... yes
checking size of uint16_t... 2
checking for int32_t... yes
checking size of int32_t... 4
checking for uint32_t... yes
checking size of uint32_t... 4
checking for int64_t... yes
checking size of int64_t... 8
checking for uint64_t... yes
checking size of uint64_t... 8
checking for int128_t... __int128
checking for uint128_t... unsigned __int128
checking for intptr_t... yes
checking size of intptr_t... 8
checking for uintptr_t... yes
checking size of uintptr_t... 8
checking for ssize_t... yes
checking size of ssize_t... 8
checking for stack end address... no
checking for uid_t in sys/types.h... (cached) yes
checking type of array argument to getgroups... (cached) gid_t
checking return type of signal handlers... void
checking for working alloca.h... yes
checking for alloca... yes
checking for dynamic size alloca... ok
checking for working memcmp... yes
checking for broken erfc of glibc-2.3.6 on IA64... no
checking for acosh... yes
checking for cbrt... yes
checking for crypt... yes
checking for dup2... yes
checking for erf... yes
checking for ffs... yes
checking for finite... yes
checking for flock... yes
checking for hypot... yes
checking for isinf... yes
checking for isnan... yes
checking for lgamma_r... yes
checking for memmove... yes
checking for nextafter... yes
checking for setproctitle... no
checking for strchr... yes
checking for strerror... yes
checking for strlcat... yes
checking for strlcpy... yes
checking for strstr... yes
checking for tgamma... yes
checking sys/pstat.h usability... no
checking sys/pstat.h presence... no
checking for sys/pstat.h... no
checking for signbit... yes
checking for pid_t... (cached) yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... (cached) no
checking for working fork... yes
checking for __syscall... yes
checking for _longjmp... yes
checking for _setjmp... no
checking for _setjmpex... no
checking for atan2l... yes
checking for atan2f... yes
checking for chroot... yes
checking for chsize... no
checking for clock_gettime... yes
checking for cosh... yes
checking for daemon... (cached) no
checking for dirfd... yes
checking for dl_iterate_phdr... no
checking for dlopen... yes
checking for dladdr... yes
checking for dup... yes
checking for dup3... no
checking for eaccess... no
checking for endgrent... yes
checking for fchmod... yes
checking for fchown... yes
checking for fcntl... yes
checking for fdatasync... (cached) no
checking for fgetattrlist... yes
checking for fmod... yes
checking for fsync... yes
checking for ftruncate... yes
checking for ftruncate64... no
checking for getattrlist... yes
checking for getcwd... yes
checking for getgidx... no
checking for getgrnam... yes
checking for getgrnam_r... yes
checking for getgroups... yes
checking for getpgid... yes
checking for getpgrp... yes
checking for getpriority... yes
checking for getpwnam_r... yes
checking for getresgid... no
checking for getresuid... no
checking for getrlimit... yes
checking for getsid... yes
checking for gettimeofday... yes
checking for getuidx... no
checking for gmtime_r... yes
checking for initgroups... yes
checking for ioctl... yes
checking for isfinite... no
checking for issetugid... yes
checking for killpg... yes
checking for lchmod... yes
checking for lchown... yes
checking for link... yes
checking for llabs... yes
checking for lockf... yes
checking for log2... yes
checking for lstat... yes
checking for malloc_usable_size... no
checking for malloc_size... yes
checking for mblen... yes
checking for memalign... no
checking for writev... yes
checking for memrchr... no
checking for memmem... yes
checking for mktime... yes
checking for pipe2... no
checking for poll... yes
checking for posix_fadvise... no
checking for posix_memalign... yes
checking for ppoll... no
checking for pread... yes
checking for qsort_r... yes
checking for readlink... yes
checking for round... yes
checking for sched_getaffinity... no
checking for seekdir... yes
checking for select_large_fdset... no
checking for sendfile... yes
checking for setegid... yes
checking for setenv... yes
checking for seteuid... yes
checking for setgid... yes
checking for setgroups... yes
checking for setpgid... yes
checking for setpgrp... yes
checking for setregid... yes
checking for setresgid... no
checking for setresuid... no
checking for setreuid... yes
checking for setrgid... yes
checking for setrlimit... yes
checking for setruid... yes
checking for setsid... yes
checking for setuid... yes
checking for shutdown... yes
checking for sigaction... yes
checking for sigaltstack... yes
checking for sigprocmask... yes
checking for sinh... yes
checking for spawnv... no
checking for symlink... yes
checking for syscall... yes
checking for sysconf... yes
checking for tanh... yes
checking for telldir... yes
checking for timegm... yes
checking for times... yes
checking for truncate... yes
checking for truncate64... no
checking for unsetenv... yes
checking for utimensat... yes
checking for utimes... yes
checking for wait4... yes
checking for waitpid... yes
checking if getcwd allocates buffer if NULL is given... yes
checking for __builtin_bswap16... yes
checking for __builtin_bswap32... yes
checking for __builtin_bswap64... yes
checking for __builtin_clz... yes
checking for __builtin_clzl... yes
checking for __builtin_clzll... yes
checking for __builtin_choose_expr... yes
checking for __builtin_choose_expr_constant_p... yes
checking for __builtin_types_compatible_p... yes
checking whether qsort_r is GNU version... no
checking whether qsort_r is BSD version... yes
checking whether atan2 handles Inf as C99... yes
checking for clock_getres... yes
checking for unsetenv returns a value... yes
checking for sigsetjmp as a macro or function... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking for struct tm.tm_gmtoff... yes
checking for external int daylight... yes
checking for external timezone... long
checking for external altzone... no
checking for timezone... yes
checking whether timezone requires zero arguments... yes
checking for negative time_t for gmtime(3)... yes
checking for localtime(3) overflow correctly... yes
checking whether right shift preserve sign bit... yes
checking whether _SC_CLK_TCK is supported... yes
checking stack growing direction on x86_64... -1
checking for pthread_kill in -lthr... no
checking for pthread_kill in -lpthread... yes
checking for pthread_np.h... no
checking whether pthread_t is scalar type... yes
checking for sched_yield... yes
checking for pthread_attr_setinheritsched... yes
checking for pthread_attr_get_np... no
checking for pthread_attr_getstack... yes
checking for pthread_get_stackaddr_np... yes
checking for pthread_get_stacksize_np... yes
checking for thr_stksegment... no
checking for pthread_stackseg_np... no
checking for pthread_getthrds_np... no
checking for pthread_cond_init... yes
checking for pthread_condattr_setclock... no
checking for pthread_condattr_init... yes
checking for pthread_sigmask... yes
checking for pthread_setname_np... yes
checking for pthread_getattr_np... no
checking for pthread_attr_init... yes
checking arguments of pthread_setname_np... (name)
checking if mcontext_t is a pointer... yes
checking for getcontext... (cached) no
checking for setcontext... (cached) no
checking if fork works with pthread... yes
checking whether ELF binaries are produced... no
checking whether OS depend dynamic link works... yes
checking whether -Wl,-undefined,dynamic_lookup is accepted as LDFLAGS... yes
checking whether -Wl,-multiply_defined,suppress is accepted as LDFLAGS... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking for backtrace in -lexecinfo... no
checking libunwind.h usability... yes
checking libunwind.h presence... yes
checking for libunwind.h... yes
checking for backtrace... yes
checking for broken backtrace... yes
checking valgrind/memcheck.h usability... no
checking valgrind/memcheck.h presence... no
checking for valgrind/memcheck.h... no
checking for strip... strip
checking whether -fPIE is accepted as CFLAGS... yes
checking whether -pie is accepted as LDFLAGS... no
checking whether -Wl,-pie is accepted as LDFLAGS... yes
checking whether dtrace USDT is available... yes
checking whether dtrace USDT is available... (cached) yes
checking whether dtrace needs post processing... no
checking for __builtin_setjmp... (cached) no
checking for setjmp type... sigsetjmp
checking for prefix of external symbols... _
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking if make is GNU make... no
checking for safe null command for make... :
checking for broken memmem... yes
checking for nroff... /usr/bin/nroff
.ext/include/x86_64-darwin17/ruby/config.h updated
ruby library version = 2.2.0
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ruby-2.2.pc
Makefile:2909: warning: overriding commands for target `ruby'
Makefile:222: warning: ignoring old commands for target `ruby'
	CC = clang
	LD = ld
	LDSHARED = clang -dynamic -bundle
	CFLAGS = -O3 -Wno-error=shorten-64-to-32  -pipe
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -fPIE
	CPPFLAGS = -I/Users/davidpell/.rbenv/versions/2.2.4/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin17 -I./include -I.
	DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -fstack-protector -Wl,-u,_objc_msgSend -Wl,-pie -framework CoreFoundation
	SOLIBS =
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
^Cmake: *** wait: Interrupted system call.  Stop.
make: *** Waiting for unfinished jobs....
make: *** [compar.o] Interrupt: 2
make: *** [class.o] Interrupt: 2
make: *** [bignum.o] Interrupt: 2
make: *** [probes.h] Interrupt: 2
make: *** [miniprelude.o] Interrupt: 2
make: *** [miniinit.o] Interrupt: 2
make: *** [dmydln.o] Interrupt: 2
make: *** [main.o] Interrupt: 2

BUILD FAILED (OS X 10.13.3 using ruby-build 20171226)

**Comment by WinglessPegasus** [comment] 2018-03-28 04:57
I met the same situation. It hanged there for a few minutes, but did complete.

**Comment by pinkopaque22** [comment] 2018-05-26 00:30
@lowderl 's workaround worked for me when nothing else did.
`RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 2.4.2`
Approx. 10 mins for me on a 2010 MBP running Sierra.

**Comment by njm2112** [comment] 2018-06-29 01:20
My install seems to be failing at the `creating: ./config.status` step:

```
configure: ruby library version = 2.5.0
configure: creating ./config.status
sed: 1: "s/.*%!_!# !%!_!#  _%!_! ...": unterminated substitute pattern
configure: error: could not make ./config.status
make: *** No targets specified and no makefile found.  Stop.

BUILD FAILED (OS X 10.12.6 using ruby-build 20180618)

Inspect or clean up the working tree at /var/folders/f2/57pztfjd22n3vj7d48stc_0c0000gn/T/ruby-build.20180628211315.44260
Results logged to /var/folders/f2/57pztfjd22n3vj7d48stc_0c0000gn/T/ruby-build.20180628211315.44260.log
```

Any advice for a workaround would be appreciated!

**Comment by Tioneb12** [comment] 2018-06-29 18:24
I have the same problem :(

➜  git:(home) ✗ RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 2.4.4
ruby-build: use openssl from homebrew
Downloading ruby-2.4.4.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.4.tar.bz2
Installing ruby-2.4.4...

BUILD FAILED (OS X 10.13.5 using ruby-build 20180618)

Inspect or clean up the working tree at /var/folders/_r/ytzkgwbd15jfz9w_csgk1jn00000gn/T/ruby-build.20180629201638.60037
Results logged to /var/folders/_r/ytzkgwbd15jfz9w_csgk1jn00000gn/T/ruby-build.20180629201638.60037.log

Last 10 log lines:
The Ruby yaml extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/ben/.rbenv/versions/2.4.4
  --with-readline-dir=/usr/local/opt/readline
  --with-openssl-dir=/usr/local/opt/openssl
  CC=clang
  CFLAGS= -O3 -Wno-error=shorten-64-to-32 
  LDFLAGS=-L/Users/ben/.rbenv/versions/2.4.4/lib 
  CPPFLAGS=-I/Users/ben/.rbenv/versions/2.4.4/include

**Comment by rraallvv** [comment] 2018-08-02 21:12
Same issue trying to install version 2.5.1

```
$ rbenv install 2.5.1
```

adding -v to the command like so `rbenv install -v 2.5.1` has no effect on the command line output

**Comment by saikyawphyowai** [comment] 2018-08-03 02:54
@lowderl thanks! it's worked...

**Comment by mislav** [comment] 2018-08-22 10:49
Closing since most people have reported that the build process is in fact just taking a longer time, but not completely hanging.

Please reopen and provide extra info if you're experiencing hanged builds for newer versions of Ruby + newer macOS.

**Closed by mislav** 2018-08-22 10:49 UTC

**Comment by Michael1969** [comment] 2018-11-08 00:39
In my case it helped to deactivate the antivirus software Avira.

**Comment by cpg94** [comment] 2018-11-25 00:40
Took a few minutes for me, patience everyone.

**Comment by thethomaseffect** [comment] 2018-11-27 14:02
I haven't seen anyone post this, but pressing the return key caused it continue for me :D

**Comment by joshuapinter** [comment] 2019-03-04 16:46
> Closing since most people have reported that the build process is in fact just taking a longer time, but not completely hanging.
> 
> Please reopen and provide extra info if you're experiencing hanged builds for newer versions of Ruby + newer macOS.

Indeed, that's what it was for me, too. Might be a UI enhancement to include some kind of progress indicator, determinate or indeterminate, just to provide transparency and alleviate these issues.

**Comment by thefonso** [comment] 2019-07-01 21:17
tried @lowderl solution for ruby 2.4.0 ... worked.  HOWEVER ... DID NOT work for ruby 1.8.6

here is the output

$ RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 1.8.6
Downloading ruby-1.8.6.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.6.tar.bz2
Installing ruby-1.8.6...

WARNING: ruby-1.8.6 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.


BUILD FAILED (OS X 10.14.2 using ruby-build 20190423)

Inspect or clean up the working tree at /var/folders/_w/98n31_kn03qfjt51p2hmrfqh0000gp/T/ruby-build.20190701171308.34043
Results logged to /var/folders/_w/98n31_kn03qfjt51p2hmrfqh0000gp/T/ruby-build.20190701171308.34043.log

Last 10 log lines:
/var/folders/_w/98n31_kn03qfjt51p2hmrfqh0000gp/T/ruby-build.20190701171308.34043 ~
/var/folders/_w/98n31_kn03qfjt51p2hmrfqh0000gp/T/ruby-build.20190701171308.34043/ruby-1.8.6 /var/folders/_w/98n31_kn03qfjt51p2hmrfqh0000gp/T/ruby-build.20190701171308.34043 ~
checking build system type... i686-apple-darwin18.2.0
checking host system type... i686-apple-darwin18.2.0
checking target system type... i686-apple-darwin18.2.0
checking for gcc... /usr/local/bin/gcc-4.2
checking for C compiler default output file name...
configure: error: C compiler cannot create executables
See `config.log' for more details.
make: *** No targets specified and no makefile found.  Stop.

Anyone know how to get this working for 1.8.6 ?

**Comment by cnees** [comment] 2020-01-13 01:07
How much patience?

For me, 6 minutes. Hope that helps!

**Comment by roeniss** [comment] 2021-02-05 05:31
After 5 minutes and it finished. Unbelievable, actually.

**Comment by zashraf1985** [comment] 2021-04-22 17:53
adding `-v` helped rule out the hanging problem.

**Comment by twome** [comment] 2021-11-28 18:52
@mislav please change the default behaviour to verbose mode, or fix the existing UI! No program should ever do anything that takes several seconds, let alone *minutes*, without telling the user why they have to wait and and trying to approximate the time remaining! In this thread alone, hundreds of probably very reasonable and smart people have been confused by this.
