### ISSUE TITLE
Ruby 2.6.0 install fails Mac 10.14

### ISSUE THREAD

**Issue by sdehority1** [rbenv/ruby-build#1281] opened 2019-02-01 21:09 UTC
Coming from The Odin Project. I'm at step 3.3 of this guide:https://www.theodinproject.com/courses/web-development-101/lessons/installing-ruby

**When I type '$ rbenv install 2.6.0 --verbose' into my terminal I get the following response:**

**BUILD FAILED** (OS X 10.14 using ruby-build 20190130)

Inspect or clean up the working tree at /var/folders/qx/_k1sd3j10zq8prq0w_cpgz880000gn/T/ruby-build.20190201142349.3477
Results logged to /var/folders/qx/_k1sd3j10zq8prq0w_cpgz880000gn/T/ruby-build.20190201142349.3477.log

Last 10 log lines:
/var/folders/qx/_k1sd3j10zq8prq0w_cpgz880000gn/T/ruby-build.20190201142349.3477/ruby-2.6.0 /var/folders/qx/_k1sd3j10zq8prq0w_cpgz880000gn/T/ruby-build.20190201142349.3477 ~
checking for ruby... /Users/samdehority/.rbenv/shims/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... x86_64-apple-darwin18.0.0
checking host system type... x86_64-apple-darwin18.0.0
checking target system type... x86_64-apple-darwin18.0.0
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
configure: error: clang version 3.0 or later is required
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Any chance you folks might be able to help me out?

**Comment by danielahampton** [comment] 2019-02-07 20:24
@sdehority1 what was your solution for the rbenv errors? I'm having the same problems, both rbenv and rails.

**Comment by sdehority1** [comment] 2019-02-08 18:01
Hey, it turned out that I had missed a step early on in the text editor section, specifically the instruction at the very bottom of this page:

https://www.theodinproject.com/courses/web-development-101/lessons/text-editors

*MacOS can do this, too, but you need to set it up. After installing VSCode, launch it any way you’re comfortable with. Once it’s running, open the Command palette with CMD + Shift + P. In the little dialog that appears, type shell command. One of the choices that appears will be Shell Command: Install 'code' command in PATH. Select that option, and restart the terminal if you have it open.*

Are you working off of a Mac? Running what's above worked for me. 

@danielahampton

**Comment by danielahampton** [comment] 2019-02-08 18:08
@sdehority1 Yeah, I'm on a Mac too. After reading through your error message, I realize mine is different. Mine's saying:
```
Last 10 log lines:
            if ((magical < 2) && !recursive && (errno == EACCES)) {
                                                ^
dir.c:2221:51: error: use of undeclared identifier 'EACCES'
            if ((magical < 2) && !recursive && (errno == EACCES)) {
                                                         ^
dir.c:3292:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
15 errors generated.
make: *** [dir.o] Error 1
```
I believe that `errno` and `EACCES` are system files, so not sure what's missing on my system that's causing ruby-build to fail.

**Comment by sdehority1** [comment] 2019-02-08 19:14
@danielahampton 

Have you ever stopped by TOP's Discord page? Every single question I've asked there has been answered. It's a bit livelier than this website, too, from what I gather. Ie there are more people participating more regularly. 

Check out the link at the bottom of this page. I cannot recommend it enough. 

https://www.theodinproject.com/courses/web-development-101/lessons/join-the-odin-community

**Comment by mislav** [comment] 2019-02-12 13:05
Closing since this is not a bug report about ruby-build. It sounds more like you had trouble setting up rbenv. Follow the installation instructions on the rbenv project page for how to install & troubleshoot it, and as far as commands in your text editor go, make sure that you've prepended the `$(rbenv root)/shims` directory to the PATH for commands run from within your editor/IDE.

**Closed by mislav** 2019-02-12 13:05 UTC
