### ISSUE TITLE
Lack of aria2c, curl and wget make rbenv install fail silently

### ISSUE THREAD

**Issue by ayghor** [rbenv/ruby-build#1116] opened 2017-07-24 15:01 UTC
EHLO,

i just installed rbenv and ruby-build and:
```
$ rbenv install 2.2.5
Downloading ruby-2.2.5.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.5.tar.bz2
$ echo $?
1
```
notice that `rbenv install 2.2.5` fail silently with exit status 1.

then i imagined out of thin air and:
```
$ cd ~/.rbenv/plugins/ruby-build/
$ grep -R wget
test/checksum.bats:  stub wget false
bin/ruby-build:  elif type wget &>/dev/null; then
bin/ruby-build:    "http_${method}_wget" "$url" "$file"
bin/ruby-build:    echo "error: please install \`aria2c\`, \`curl\` or \`wget\` and try again" >&2
bin/ruby-build:http_head_wget() {
bin/ruby-build:  wget -q --spider ${WGET_OPTS} "$1" >&4 2>&1
bin/ruby-build:http_get_wget() {
bin/ruby-build:  wget -nv ${WGET_OPTS} -O "${2:--}" "$1"
```
it was teh case that i didnt have `wget`, `curl` or `aria2c`, but no warning was shown!

<3

**Comment by alexanderadam** [comment] 2017-09-19 11:06
It seems to be a duplicate of [issue 1058](https://github.com/rbenv/ruby-build/issues/1058) for me.

**Comment by ayghor** [comment] 2017-09-21 04:51
indeed it seems

**Comment by mislav** [comment] 2018-08-22 11:34
Closing as duplicate

**Closed by mislav** 2018-08-22 11:34 UTC
