### ISSUE TITLE
error: use of undeclared identifier 'errno'

### ISSUE THREAD

**Issue by DaNyNaNd** [rbenv/ruby-build#1286] opened 2019-02-13 15:11 UTC
When I run `rbenv install 2.6.1` I'm getting this error:

```
cont.c:897:9: error: use of undeclared identifier 'errno'
        errno = 0;
        ^
cont.c:900:80: error: use of undeclared identifier 'errno'
            rb_raise(rb_eFiberError, "can't alloc machine stack to fiber: %s", ERRNOMSG);
                                                                               ^
cont.c:862:27: note: expanded from macro 'ERRNOMSG'
#define ERRNOMSG strerror(errno)
                          ^
cont.c:906:68: error: use of undeclared identifier 'errno'
            rb_raise(rb_eFiberError, "can't set a guard page: %s", ERRNOMSG);
                                                                   ^
cont.c:862:27: note: expanded from macro 'ERRNOMSG'
#define ERRNOMSG strerror(errno)
                          ^
3 errors generated.
dir.c:562:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
dir.c:567:16: error: use of undeclared identifier 'EIO'
        else if (e == EIO) {
                      ^
make: *** [cont.o] Error 1
make: *** Waiting for unfinished jobs....
dir.c:788:5: error: use of undeclared identifier 'errno'
    errno = 0;
    ^
dir.c:793:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
dir.c:1363:17: error: use of undeclared identifier 'ENOENT'
    return e == ENOENT || e == ENOTDIR;
                ^
dir.c:1363:32: error: use of undeclared identifier 'ENOTDIR'
    return e == ENOENT || e == ENOTDIR;
                               ^
dir.c:1401:35: error: use of undeclared identifier 'errno'
    if (ret < 0 && !to_be_ignored(errno))
                                  ^
dir.c:1416:35: error: use of undeclared identifier 'errno'
    if (ret < 0 && !to_be_ignored(errno))
                                  ^
dir.c:1463:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
dir.c:1516:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
dir.c:1804:21: error: use of undeclared identifier 'errno'
        if (!to_be_ignored(errno))
                           ^
dir.c:1993:18: error: use of undeclared identifier 'EACCES'
    if (error == EACCES) {
                 ^
dir.c:2221:42: error: use of undeclared identifier 'errno'
            if ((magical < 2) && !recursive && (errno == EACCES)) {
                                                ^
dir.c:2221:51: error: use of undeclared identifier 'EACCES'
            if ((magical < 2) && !recursive && (errno == EACCES)) {
                                                         ^
dir.c:3292:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
15 errors generated.
make: *** [dir.o] Error 1

BUILD FAILED (OS X 10.14.3 using ruby-build 20190130)

Inspect or clean up the working tree at /var/folders/kn/4ntvx6_x1_181ttn4_q2wp900000gn/T/ruby-build.20190213090639.45693
Results logged to /var/folders/kn/4ntvx6_x1_181ttn4_q2wp900000gn/T/ruby-build.20190213090639.45693.log

Last 10 log lines:
            if ((magical < 2) && !recursive && (errno == EACCES)) {
                                                ^
dir.c:2221:51: error: use of undeclared identifier 'EACCES'
            if ((magical < 2) && !recursive && (errno == EACCES)) {
                                                         ^
dir.c:3292:10: error: use of undeclared identifier 'errno'
        int e = errno;
                ^
15 errors generated.
make: *** [dir.o] Error 1
```

Here is the config output:
```
Configuration summary for ruby version 2.6.1

   * Installation prefix: /Users/danielhampton/.rbenv/versions/2.6.1
   * exec prefix:         ${prefix}
   * arch:                x86_64-darwin18
   * site arch:           ${arch}
   * RUBY_BASE_NAME:      ruby
   * ruby lib prefix:     ${libdir}/${RUBY_BASE_NAME}
   * site libraries path: ${rubylibprefix}/${sitearch}
   * vendor path:         ${rubylibprefix}/vendor_ruby
   * target OS:           darwin18
   * compiler:            clang
   * with pthread:        yes
   * enable shared libs:  no
   * dynamic library ext: bundle
   * CFLAGS:              ${optflags} ${debugflags} ${warnflags}
   * LDFLAGS:             -L. \
                          -L/Users/danielhampton/.rbenv/versions/2.6.1/lib  \
                          -fstack-protector-strong -L/usr/local/lib
   * DLDFLAGS:            -L/Users/danielhampton/.rbenv/versions/2.6.1/lib  \
                          -Wl,-undefined,dynamic_lookup \
                          -Wl,-multiply_defined,suppress
   * optflags:            -O3
   * debugflags:          -ggdb3
   * warnflags:           -Wall -Wextra -Wdeclaration-after-statement \
                          -Wdeprecated-declarations -Wdivision-by-zero \
                          -Wimplicit-function-declaration -Wimplicit-int \
                          -Wpointer-arith -Wshorten-64-to-32 \
                          -Wwrite-strings -Wmissing-noreturn \
                          -Wno-constant-logical-operand -Wno-long-long \
                          -Wno-missing-field-initializers \
                          -Wno-overlength-strings -Wno-parentheses-equality \
                          -Wno-self-assign -Wno-tautological-compare \
                          -Wno-unused-parameter -Wno-unused-value \
                          -Wunused-variable -Wextra-tokens
   * strip command:       strip -A -n
   * install doc:         yes
   * JIT support:         yes
   * man page type:       doc

---
	BASERUBY = /usr/bin/ruby --disable=gems
	CC = clang
	LD = ld
	LDSHARED = clang -dynamiclib
	CFLAGS = -O3 -Wno-error=shorten-64-to-32  -pipe
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -fPIE -DCANONICALIZATION_FOR_MATHN
	CPPFLAGS = -I/Users/danielhampton/.rbenv/versions/2.6.1/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin18 -I./include -I. -I./enc/unicode/11.0.0
	DLDFLAGS = -L/Users/danielhampton/.rbenv/versions/2.6.1/lib  -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -fstack-protector-strong -Wl,-pie -framework Security -framework Foundation
	SOLIBS = -lpthread -ldl -lobjc
	LANG = en_US.UTF-8
	LC_ALL =
	LC_CTYPE = en_US.UTF-8
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
```

Any ideas? I've tried SO, Apple Dev Forums, and a couple other places with no luck.

**Comment by danielahampton** [comment] 2019-02-21 21:30
Any update on this? I just updated to macOS 10.14.4 Beta 3, but the issue is still persisting.

**Comment by mislav** [comment] 2019-11-04 16:14
@DaNyNaNd Sorry this hasn't got any attention. We didn't have any useful advice for you.

Is still still an issue?

**Comment by hsbt** [comment] 2020-07-22 06:39
This issues was happend with Beta version. We will close this.

@DaNyNaNd If you still have this issue, Can you update the current status? Thanks.

**Closed by hsbt** 2020-07-22 06:39 UTC
