### ISSUE TITLE
Can't install ruby 2.2.10

### ISSUE THREAD

**Issue by angarc** [rbenv/ruby-build#1764] opened 2021-05-05 15:16 UTC
I'm trying to install a pretty old version of ruby. I know that openssl is a problem for older versions, so I tried using this command to install this particular version:

```
brew --prefix openssl@1.0
export LDFLAGS="-L/usr/local/opt/openssl@1.0/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.0/include"
CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" rbenv install 2.2.10
```

And after waiting a couple of minutes, this is the final output before it all falls a cliff:

```
ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.2.1 using ruby-build 20201225)

Inspect or clean up the working tree at /var/folders/t1/6bjcvvp54plcf6qktlyn68c40000gn/T/ruby-build.20210505091205.92478.hBiXkT
Results logged to /var/folders/t1/6bjcvvp54plcf6qktlyn68c40000gn/T/ruby-build.20210505091205.92478.log

Last 10 log lines:
compiling eval.c
compiling load.c
encoding.c:825:2: error: implicit declaration of function 'rb_str_change_terminator_length' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rb_str_change_terminator_length(obj, oldtermlen, termlen);
        ^
compiling proc.c
compiling file.c
1 error generated.
make: *** [encoding.o] Error 1
make: *** Waiting for unfinished jobs....
```

I've tried looking up this particular C involved error, and had no luck, hence my asking here.

Any help is appreciated!

**Comment by eddroid** [comment] 2021-05-20 19:35
dupe of https://github.com/rbenv/ruby-build/issues/1489

**Closed** 2021-05-21 00:16 UTC
